# Generated by Django 3.0 on 2019-12-17 11:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0002_auto_20191217_1705'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordercontent',
            name='meal',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='food.Meal'),
        ),
        migrations.AlterField(
            model_name='ordercontent',
            name='order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='meals', to='food.Order'),
        ),
    ]
