# Generated by Django 3.0 on 2019-12-17 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0004_auto_20191217_1708'),
    ]

    operations = [
        migrations.RenameField(
            model_name='check',
            old_name='order',
            new_name='orders',
        ),
    ]
