# Generated by Django 3.0 on 2019-12-17 11:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0005_auto_20191217_1709'),
    ]

    operations = [
        migrations.AlterField(
            model_name='check',
            name='orders',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='food.Order'),
        ),
    ]
