# Generated by Django 3.0 on 2019-12-17 12:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0008_auto_20191217_1800'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='check',
            name='orders',
        ),
        migrations.RemoveField(
            model_name='check',
            name='percentage',
        ),
        migrations.AddField(
            model_name='check',
            name='orderid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order', to='food.Order'),
        ),
        migrations.AddField(
            model_name='check',
            name='servicefee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='servicefee', to='food.ServicePercentage'),
        ),
        migrations.AlterField(
            model_name='check',
            name='date',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='department',
            name='name',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='role',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='table',
            name='name',
            field=models.CharField(default='', max_length=200),
        ),
    ]
